In [1]:
import numpy as np

2.1.2


In [126]:

def to_2d(array:np.array, cols) -> np.array:
    if not isinstance(cols, int):
        raise ValueError(f"Rows must be integer, got {type(cols)}")
    if array.size % cols == 0:
        return  array.reshape(-1, cols)
    raise ValueError(f"The number of cols must be a multiple of {array.size}! Got {rows}.")

def get_arr() -> np.array:
    # функція для оновлення масива, щоб не крутити мишкою по документу =)
    return np.genfromtxt(fname="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", dtype=np.float16, usecols=(0, 1, 2, 3), delimiter=",")

Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [127]:
arr = get_arr()

Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

In [88]:
if arr.ndim != 2:
    arr = to_2d(arr, cols=4)
    msg = "reshaped to 2D!"
else:
    msg = "already 2D!"
print(msg , arr.shape)


already 2D! (150, 4)


Порахувати mean, median, standard deviation для 1-ї колонки

In [89]:
row1 = arr[0]
arr_mean1 = np.mean(row1)
arr_median1 = np.median(row1) # функція впорядковує значення автоматично, тож перед її застосуванням немає необхідності це робити
arr_std_1 = np.std(row1)

print(f"row {row1}:\nmean: {arr_mean1}\nmedian: {arr_median1}\nstandard deviation: {arr_std_1}")


row [5.1 3.5 1.4 0.2]:
mean: 2.55078125
median: 2.44921875
standard deviation: 1.888671875


Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)


In [146]:
arr = get_arr()
count_nans = 20
mode = input("Оберіть варіант: ")  # щоб не гратись з коментуванням коду
if mode == "1":
    #Варіант 1 - nan в строках НЕ повторюється
    random_rows = np.random.choice(arr.shape[0], count_nans, replace=False) # Обираємо 20 випадкових строк, строки повторюватись не будуть - це гарантує унікальність
    random_colls = np.random.choice(arr.shape[1], count_nans, replace=True) # обираємо 20 випадкових колонок, номери колонок повторюються так як arr.shape[1] < count_nans
    indexes = np.column_stack((random_rows, random_colls)) # створюємо масив 20, 2 з наших векторів (це буде масив координат)
    arr[(indexes[:, 0], indexes[:, 1])] = np.nan # присвоїли  значення кожній координаті в масиві
    # arr[indexes] = np.nan # присвоїли  значення кожній координаті в масиві
else:
    #Варіант 2 - nan може повторюватись в строках
    colls = arr.shape[1]
    arr = arr.flatten()  # перетворили матрицю у вектор
    indexes = np.random.choice(arr.size, count_nans, replace=False) # обрали будь-який елемент 
    arr[indexes] = np.nan # присвоїли обраним елементам значення
    arr = to_2d(arr, colls) # зібрали вектор обратно в матрицю

total_nans = np.isnan(arr) # створили булеву маску
print(f"nan_count: {total_nans.sum()}") # порахували суму всіх елементів, завдяки тому що True - це булева одиниця


nan_count: 20


Знайти позиції вставлених значень np.nan в 1-й колонці

In [162]:
column1 = arr[:, 0] # отримали першу колонку
print(column1)
nan_pos = np.where(np.isnan(column1))[0] # знайшли всі nan в колонці. [0] щоб отримати вектор, бо np.where() повертає кортеж
print(nan_pos)

[5.1 4.9 4.7 nan 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 nan 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 nan 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 nan 6.1 7.7 6.3 6.4 nan 6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
[  3  87 123 133 138]


Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [171]:
# я так зрозумів, що обидві умови мають виконуватись одночасно
column3 = arr[:, 2]
filtered_col1_3 = arr[(column3 > 1.5) & (column1 < 5.0)] 
print(filtered_col1_3)



[[4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.5 4.5 1.7]]


Замінити всі значення np.nan на 0

In [175]:
arr = np.nan_to_num(arr, nan=0)
print("nan count: ", np.isnan(arr).sum())

nan count:  0


Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

In [186]:
val, count = np.unique(arr, return_counts=True) # можна було б скопіювати з лекції, але де в цьому романтика...
unique_vals = np.column_stack((val, count))
print(unique_vals)

[[ 0.         20.        ]
 [ 0.09997559  5.        ]
 [ 0.19995117 28.        ]
 [ 0.30004883  6.        ]
 [ 0.39990234  7.        ]
 [ 0.5         1.        ]
 [ 0.60009766  1.        ]
 [ 1.          8.        ]
 [ 1.09960938  4.        ]
 [ 1.20019531  7.        ]
 [ 1.29980469 18.        ]
 [ 1.40039062 19.        ]
 [ 1.5        26.        ]
 [ 1.59960938 10.        ]
 [ 1.70019531  6.        ]
 [ 1.79980469 12.        ]
 [ 1.90039062  7.        ]
 [ 2.          7.        ]
 [ 2.09960938  6.        ]
 [ 2.19921875  6.        ]
 [ 2.30078125 12.        ]
 [ 2.40039062  6.        ]
 [ 2.5        11.        ]
 [ 2.59960938  4.        ]
 [ 2.69921875  8.        ]
 [ 2.80078125 13.        ]
 [ 2.90039062  9.        ]
 [ 3.         26.        ]
 [ 3.09960938 12.        ]
 [ 3.19921875 12.        ]
 [ 3.30078125  7.        ]
 [ 3.40039062 12.        ]
 [ 3.5         8.        ]
 [ 3.59960938  4.        ]
 [ 3.69921875  4.        ]
 [ 3.80078125  7.        ]
 [ 3.90039062  5.        ]
 

Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [204]:
parts = 2
splited_arr = np.array_split(arr, parts, axis=0)
shapes = [f"arr{num+1}: {i.shape}" for num, i in enumerate(splited_arr)] # я чув про for, але це суто для універсальності вивода
print(shapes)

['arr1: (75, 4)', 'arr2: (75, 4)']


Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [238]:
arr1, arr2, *_ = splited_arr

indxs1 = np.argsort(arr1[:, 0]) # отримуємо відсортовані індекси елементів першої колонки 
arr1 = arr1[indxs1] # сортуємо масив зі збереженням зві'язку даних в рядках

indxs2 = np.argsort(arr2[:, 0])[::-1] # індекси у зворотньому порядку
arr2 = arr2[indxs2]# сортуємо масив зі збереженням зві'язку даних в рядках

# print(arr1)
# print(arr2)


Зібрати обидва массиви в одне ціле

In [240]:
arr = np.concatenate((arr1, arr2), axis=0)
# print(arr1_2)

Знайти найбільш часто повторюване значення в массиві

In [252]:
most_repeated_index = np.argmax(unique_vals[:, 1]) # отримали індекс строки з максимальним значенням у першій колонці (у справжнього програміста перша дитина - нульова)
most_repeated_val = unique_vals[most_repeated_index, 0] # витягнув значення з нульової колонки, яке відповідає потрібному нам рядку
print(f"val {most_repeated_val} is counted {most_repeated_index} times in the array")
# використав unique_vals так як невзираючи на те що я модифікував матрицю - значення та їх кількість в ній не змінились, тільки розташування


val 0.199951171875 is counted 2 times in the array


Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [288]:
def column_modifier(column:np.array, multiplyer=2, delimiter=4, save_orig:bool=True) -> np.array:
    mean = np.mean(column)
    if save_orig:  # з умови не ясно чи має зберігатись оригінальна колонка в масиві, тож от
        column = column.copy()
    column[column < mean] *= multiplyer
    column[column >= mean] /= delimiter
    return column



Застосувати отриману функцію до 3-ї колонки

In [292]:
modified_column = column_modifier(arr[:, 2])
modified_column

array([3.   , 2.2  , 2.8  , 2.6  , 2.6  , 2.6  , 2.8  , 2.8  , 2.   ,
       2.6  , 3.2  , 2.8  , 2.8  , 0.95 , 3.2  , 0.   , 3.   , 3.   ,
       0.   , 3.   , 2.8  , 3.2  , 2.8  , 2.6  , 3.   , 3.2  , 3.2  ,
       1.75 , 2.8  , 2.4  , 0.95 , 3.   , 3.2  , 2.8  , 2.8  , 3.   ,
       3.   , 3.4  , 0.975, 3.   , 2.8  , 3.   , 3.   , 2.6  , 3.4  ,
       3.   , 3.4  , 3.   , 2.6  , 1.   , 2.8  , 1.8  , 1.125, 0.975,
       3.4  , 1.125, 3.   , 1.025, 2.4  , 1.2  , 1.05 , 1.   , 1.   ,
       1.175, 1.175, 1.125, 1.175, 1.225, 1.075, 1.125, 1.15 , 1.15 ,
       1.1  , 1.225, 1.175, 1.6  , 1.675, 1.725, 1.675, 1.525, 1.65 ,
       1.525, 1.575, 1.45 , 1.525, 1.5  , 1.475, 1.35 , 1.275, 1.425,
       1.475, 1.2  , 1.375, 1.425, 1.4  , 1.45 , 1.175, 1.425, 1.3  ,
       1.25 , 1.1  , 1.3  , 1.45 , 1.375, 0.   , 1.325, 1.325, 1.4  ,
       1.4  , 1.375, 1.4  , 1.4  , 1.25 , 1.5  , 1.35 , 1.2  , 1.075,
       0.   , 1.15 , 1.225, 1.125, 1.25 , 1.275, 1.125, 1.275, 1.   ,
       0.975, 1.275,